[package]
name = "nixme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.15.0"
inquire = "0.5.2"
is_sudo = "0.0.1"
libc = "0.2.137"
log = "0.4.17"
thiserror = "1.0.37"
